// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"time"
)

type Article struct {
	ID          int64     `json:"id"`
	Guid        string    `json:"guid"`
	Title       string    `json:"title"`
	Body        string    `json:"body"`
	PublishedAt time.Time `json:"published_at"`
	Link        string    `json:"link"`
	Details     string    `json:"details"`
	Feed        string    `json:"feed"`
	Read        bool      `json:"read"`
	Bookmarked  bool      `json:"bookmarked"`
}

type Session struct {
	Token  interface{} `json:"token"`
	Data   []byte      `json:"data"`
	Expiry interface{} `json:"expiry"`
}
